In [1]:
import pandas as pd
import geopandas as gpd

In [15]:
gdf = gpd.read_file('/Users/judetak/Desktop/산공카르텔경진대회/서울시 토지피복도/서울시_토지피복도.gpkg')

In [16]:
gdf

,L2_CODE,L2_NAME,IMG_NAME,IMG_DATE,ETC_INFO,UD_INFO,INX_NUM,layer,path,geometry
0,330,혼효림,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,376082,lv2_376082,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((199921.632 564908.535, 199949...."
1,320,침엽수림,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,376082,lv2_376082,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((199804.308 564865.383, 199809...."
2,320,침엽수림,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,376082,lv2_376082,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((199809.308 564855.383, 199814...."
3,320,침엽수림,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,376082,lv2_376082,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((199814.308 564850.383, 199819...."
4,320,침엽수림,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,376082,lv2_376082,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((199819.308 564845.383, 199824...."
...,...,...,...,...,...,...,...,...,...,...
57035,420,인공초지,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,377092,lv2_377092,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((211067.107 540931.837, 211064...."
57036,150,교통지역,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,377092,lv2_377092,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((211581.6 540935.393, 211577.70..."
57037,420,인공초지,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,377092,lv2_377092,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((211622.841 540955.623, 211621...."
57038,620,인공나지,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,377092,lv2_377092,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((211688.809 540986.066, 211681...."
57039,150,교통지역,항공정사영상,2024-12-31,None,2025년 사업-세분류 토지피복지도,377092,lv2_377092,/Users/judetak/Desktop/산공카르텔경진대회...,"MULTIPOLYGON (((214229.305 544400.008, 214226...."

In [17]:
gdf = gdf.drop(columns= ['ETC_INFO','INX_NUM','layer','path'])

In [18]:
list(gdf['L2_NAME'].unique())

['혼효림',
 '침엽수림',
 '자연나지',
 '활엽수림',
 '내륙수',
 '내륙습지',
 '주거지역',
 '교통지역',
 '인공나지',
 '인공초지',
 '밭',
 '기타재배지',
 '상업지역',
 '자연초지',
 '공공시설지역',
 '시설재배지',
 '문화·체육·휴양지역',
 '논',
 '과수원',
 '공업지역']

In [19]:
category_mapping = {
    # 1. Green space (녹지)
    '혼효림': 'Green space',
    '침엽수림': 'Green space',
    '활엽수림': 'Green space',
    '자연초지': 'Green space',
    '인공초지': 'Green space',
    
    # 2. River zone (하천)
    '내륙수': 'River zone',
    '내륙습지': 'River zone',
    
    # 3. Road area (도로 시설물)
    '교통지역': 'Road area',
    
    # 4. Buildings (건물)
    '주거지역': 'Buildings',
    '상업지역': 'Buildings',
    '공업지역': 'Buildings',
    '공공시설지역': 'Buildings'
}

In [20]:
gdf['category'] = gdf['L2_NAME'].map(category_mapping)

In [21]:
gdf

,L2_CODE,L2_NAME,IMG_NAME,IMG_DATE,UD_INFO,geometry,category
0,330,혼효림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199921.632 564908.535, 199949....",Green space
1,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199804.308 564865.383, 199809....",Green space
2,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199809.308 564855.383, 199814....",Green space
3,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199814.308 564850.383, 199819....",Green space
4,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199819.308 564845.383, 199824....",Green space
...,...,...,...,...,...,...,...
57035,420,인공초지,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211067.107 540931.837, 211064....",Green space
57036,150,교통지역,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211581.6 540935.393, 211577.70...",Road area
57037,420,인공초지,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211622.841 540955.623, 211621....",Green space
57038,620,인공나지,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211688.809 540986.066, 211681....",NaN
57039,150,교통지역,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((214229.305 544400.008, 214226....",Road area

In [22]:
# 해당 행(폴리곤)의 면적을 계산하여 'area' 컬럼에 저장
gdf['area(m2)'] = gdf.geometry.area

In [23]:
gdf

,L2_CODE,L2_NAME,IMG_NAME,IMG_DATE,UD_INFO,geometry,category,area(m2)
0,330,혼효림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199921.632 564908.535, 199949....",Green space,3.129639e+03
1,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199804.308 564865.383, 199809....",Green space,5.000000e+01
2,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199809.308 564855.383, 199814....",Green space,2.500000e+01
3,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199814.308 564850.383, 199819....",Green space,2.500000e+01
4,320,침엽수림,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((199819.308 564845.383, 199824....",Green space,5.000000e+01
...,...,...,...,...,...,...,...,...
57035,420,인공초지,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211067.107 540931.837, 211064....",Green space,2.314597e+02
57036,150,교통지역,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211581.6 540935.393, 211577.70...",Road area,3.608902e+04
57037,420,인공초지,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211622.841 540955.623, 211621....",Green space,2.735912e+04
57038,620,인공나지,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((211688.809 540986.066, 211681....",NaN,5.076572e+03
57039,150,교통지역,항공정사영상,2024-12-31,2025년 사업-세분류 토지피복지도,"MULTIPOLYGON (((214229.305 544400.008, 214226....",Road area,1.506109e+06

In [24]:
gdf.to_file('서울시 토지피복도_categorized.gpkg',driver='gpkg')

In [2]:
gdf = gpd.read_file('/Users/judetak/Desktop/산공카르텔경진대회/서울시 토지피복도_격자_250M.gpkg')

In [6]:
gdf['reclass'].unique()

<StringArray>
['buildings', 'greenspace', 'road struc', 'river zone']
Length: 4, dtype: str

In [7]:
# 1. 각 잘려진 폴리곤(조각)의 면적 계산
# 주의: 면적을 정확히 계산하려면 gdf의 좌표계가 미터(m) 단위인 투영좌표계(예: EPSG:5179)여야 합니다.
gdf['area'] = gdf.geometry.area

# 2. 피벗 테이블을 사용하여 CELL_ID별, reclass별 면적 합계 구하기
pivot_df = gdf.pivot_table(
    index='CELL_ID', 
    columns='reclass', 
    values='area', 
    aggfunc='sum', 
    fill_value=0  # 해당 피복이 없는 경우 0으로 채움
)

# 3. 각 그리드의 전체 면적 계산 (조각난 면적들의 총합)
pivot_df['total_area'] = pivot_df.sum(axis=1)

# 4. 재분류된 4가지 항목을 퍼센트(%)로 변환 (0 ~ 100%)
target_classes = ['buildings', 'greenspace', 'road struc', 'river zone']

for col in target_classes:
    if col in pivot_df.columns:
        # 해당 피복 면적 / 전체 면적 * 100
        pivot_df[col] = (pivot_df[col] / pivot_df['total_area']) * 100
    else:
        # 데이터 전체에 해당 피복이 아예 없을 경우 0 칼럼 생성
        pivot_df[col] = 0.0

# 퍼센트 계산 후 불필요한 전체 면적 칼럼은 제거
pivot_df = pivot_df.drop(columns=['total_area']).reset_index()

# 5. 원래 그리드가 가지고 있던 고유 정보들(CELL_X, CELL_Y, GID, lon, lat) 추출
# 같은 CELL_ID를 가진 행들 중 첫 번째 행의 정보만 가져와서 중복 제거
grid_info = gdf[['CELL_ID', 'CELL_X', 'CELL_Y', 'GID', 'lon', 'lat']].drop_duplicates(subset=['CELL_ID'])

# 6. 조각난 Geometry(도형)를 다시 하나의 그리드 사각형으로 합치기 (Dissolve)
# 잘려진 조각들을 CELL_ID 기준으로 다시 병합하여 원래의 네모난 그리드 형상으로 복구합니다.
grid_geom = gdf[['CELL_ID', 'geometry']].dissolve(by='CELL_ID').reset_index()

# 7. 속성 정보, 면적 비율(%), 도형(Geometry)을 모두 하나로 병합(Merge)
# grid_info + 퍼센트 데이터
final_df = pd.merge(grid_info, pivot_df, on='CELL_ID', how='left')
# + 도형 데이터
final_df = pd.merge(final_df, grid_geom, on='CELL_ID', how='left')

# 8. 최종 결과를 GeoDataFrame으로 변환 및 원하는 칼럼 순서로 정리
final_gdf = gpd.GeoDataFrame(final_df, geometry='geometry', crs=gdf.crs)

# 요구하신 칼럼 구성(순서)대로 맞추기
columns_order = [
    'CELL_ID', 'buildings', 'greenspace', 'road struc', 'river zone', 
    'CELL_X', 'CELL_Y', 'GID', 'lon', 'lat', 'geometry'
]
final_gdf = final_gdf[columns_order]

# 결과 확인
print(final_gdf.head())

/var/folders/pk/6tlj8j4n5b90lwc_4d4rr51m0000gn/T/ipykernel_42225/16963984.py:3: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf['area'] = gdf.geometry.area
/opt/miniconda3/envs/engineering/lib/python3.11/site-packages/shapely/set_operations.py:553: RuntimeWarning: invalid value encountered in unary_union
  return lib.unary_union(collections, **kwargs)

      CELL_ID  buildings  greenspace  road struc  river zone  CELL_X   CELL_Y  \
0  다사55004100   0.810959   99.189041    0.000000    0.000000  955125  1941125
1  다사55004050   0.221215   95.703069    0.000000    4.075716  955125  1940625
2  다사54754050  42.731537   53.487937    3.780527    0.000000  954875  1940625
3  다사54754075  76.795168   21.500419    1.468049    0.236363  954875  1940875
4  다사54754100  50.859004   49.140996    0.000000    0.000000  954875  1941125

          GID         lon        lat  \
0  다사55aa41aa  126.991103  37.469385
1  다사55aa40ba  126.991133  37.464878
2  다사54bb40ba  126.988306  37.464866
3  다사54bb40bb  126.988291  37.467119
4  다사54bb41aa  126.988275  37.469372

                                            geometry
0  POLYGON ((126.99394 37.46794, 126.99394 37.467...
1  POLYGON ((126.99114 37.46442, 126.99113 37.464...
2  POLYGON ((126.98948 37.46261, 126.98931 37.462...
3  POLYGON ((126.98831 37.46485, 126.9883 37.4656...
4  POLYGON ((126.98829 37.46711, 126.98829 37.467...

In [8]:
final_gdf.to_file('grid_landcover_percentage.shp', encoding='utf-8')
final_gdf.drop(columns='geometry').to_csv('grid_landcover_percentage.csv', index=False, encoding='utf-8-sig')

In [23]:
import math

# 1. 관측소 데이터 불러오기 및 GeoDataFrame 변환
stations_df = pd.read_csv('/Users/judetak/Desktop/산공카르텔경진대회/seoul_stations.csv')

# 관측소를 구분할 고유 ID 칼럼 설정 (이름이 '측정소명' 등이라면 해당 칼럼으로 변경하세요)
# 만약 고유 ID가 없다면 인덱스를 ID로 만듭니다.
station_id_col = 'station_name' 
if station_id_col not in stations_df.columns:
    stations_df['station_id'] = stations_df.index
    station_id_col = 'station_id'

# dmX(경도), dmY(위도)를 이용해 WGS84(EPSG:4326) 포인트 지오메트리 생성
stations_gdf = gpd.GeoDataFrame(
    stations_df,
    geometry=gpd.points_from_xy(stations_df['dmY'], stations_df['dmX']), # 순서 교체! (dmY=경도, dmX=위도)
    crs="EPSG:4326"
)
# 2. 미터 단위 좌표계(KOREA 2000 / EPSG:5179)로 변환 (버퍼를 m 단위로 치기 위함)
stations_gdf = stations_gdf.to_crs(epsg=5179)

# ⚠️ 주의: 기존 토지피복 데이터도 교차 연산을 위해 동일한 좌표계로 맞춰져 있어야 합니다.
landcover_gdf = gdf.to_crs(epsg=5179)

# 3. 버퍼 거리 및 타겟 변수 설정
buffer_distances = [100, 500, 1000, 2000]
target_classes = ['greenspace', 'river zone', 'road struc', 'buildings']

# 각 버퍼 거리별 결과를 담을 리스트
buffer_results = []

for dist in buffer_distances:
    print(f"{dist}m 버퍼 연산 중...")
    
    # 3-1. 관측소 기준 원형 버퍼 생성
    buffered_stations = stations_gdf.copy()
    buffered_stations.geometry = buffered_stations.buffer(dist)
    
    # 원형 버퍼의 이론적 전체 면적 (원주율 * r^2)
    buffered_stations['buffer_area'] = math.pi * (dist ** 2)
    
    # 3-2. 버퍼 영역과 토지피복도 교차 연산 (Intersect)
    # 버퍼 안으로 들어오는 토지피복 폴리곤만 쿠키틀처럼 잘라냅니다.
    intersected = gpd.overlay(buffered_stations, landcover_gdf, how='intersection')
    
    # 3-3. 잘려진 토지피복의 실제 면적 계산
    intersected['intersect_area'] = intersected.geometry.area
    
    # 3-4. 관측소별, 피복(reclass)별 면적 합계 구하기 (Pivot)
    pivot_df = intersected.pivot_table(
        index=station_id_col,
        columns='reclass',
        values='intersect_area',
        aggfunc='sum',
        fill_value=0
    )
    
    # 3-5. 전체 버퍼 면적 대비 비율(%) 계산
    for col in target_classes:
        if col in pivot_df.columns:
            # 관측소별 전체 버퍼 면적으로 나누기
            buffer_areas = buffered_stations.set_index(station_id_col)['buffer_area']
            pivot_df[col] = (pivot_df[col] / buffer_areas) * 100
        else:
            pivot_df[col] = 0.0  # 해당 반경 내에 그 피복이 아예 없으면 0
            
    # 칼럼 이름에 버퍼 거리 명시 (예: 100m_greenspace)
    pivot_df = pivot_df[target_classes] # 지정한 4개 칼럼만 남기고 순서 정렬
    pivot_df.columns = [f"{dist}m_{col}" for col in pivot_df.columns]
    
    buffer_results.append(pivot_df)

# 4. 모든 버퍼 반경(100, 500, 1000, 2000)의 결과를 하나로 가로 병합
all_buffers_df = pd.concat(buffer_results, axis=1).reset_index()

# 5. 원본 관측소 데이터(위경도 등 포함)와 최종 병합
final_station_df = pd.merge(stations_df, all_buffers_df, on=station_id_col, how='left')

# 버퍼 안에 육지 자체가 없거나 누락된 경우 NaN이 뜰 수 있으므로 0으로 채움
final_station_df = final_station_df.fillna(0)

# 결과 확인
print(final_station_df.head())

100m 버퍼 연산 중...

/opt/miniconda3/envs/engineering/lib/python3.11/site-packages/shapely/set_operations.py:168: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

500m 버퍼 연산 중...

/opt/miniconda3/envs/engineering/lib/python3.11/site-packages/shapely/set_operations.py:168: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

1000m 버퍼 연산 중...

/opt/miniconda3/envs/engineering/lib/python3.11/site-packages/shapely/set_operations.py:168: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

2000m 버퍼 연산 중...

/opt/miniconda3/envs/engineering/lib/python3.11/site-packages/shapely/set_operations.py:168: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)

         dmX                           item mangName  year  \
0  37.564639  SO2, CO, O3, NO2, PM10, PM2.5     도시대기  1995
1  37.549389  SO2, CO, O3, NO2, PM10, PM2.5    도로변대기  1996
2  37.572025  SO2, CO, O3, NO2, PM10, PM2.5     도시대기  1997
3  37.568650  SO2, CO, O3, NO2, PM10, PM2.5    도로변대기  1994
4  37.570633  SO2, CO, O3, NO2, PM10, PM2.5    도로변대기  2008

                               addr stationName         dmY  station_id  \
0          서울 중구 덕수궁길 15 시청서소문별관 3동          중구  126.975961           0
1           서울 용산구 한강대로 405 (서울역 앞)        한강대로  126.971519           1
2    서울 종로구 종로35가길 19 종로5,6가 동 주민센터         종로구  127.005028           2
3  서울 중구 청계천로 184 (청계천4가사거리 남강빌딩 앞)        청계천로  126.998083           3
4           서울 종로구 종로 169 (종묘주차장 앞)          종로  126.996783           4

   100m_greenspace  100m_river zone  ...  500m_road struc  500m_buildings  \
0        39.091521         0.000000  ...        25.608397       59.712613
1         9.870937         0.000000  ...        19.645211       78.064352
2         0.000000         0.000000  ...        21.621246       70.953273
3         0.000000         6.650604  ...        23.188430       67.612231
4         7.694860         0.000000  ...        22.586301       61.755334

   1000m_greenspace  1000m_river zone  1000m_road struc  1000m_buildings  \
0          9.314949          0.295662         29.108918        61.119910
1         15.126995          0.000000         16.492650        68.219795
2         11.262965          0.632855         18.725218        69.218406
3          9.121394          0.681107         22.726278        67.310660
4         11.945378          0.693167         21.002850        66.198042

   2000m_greenspace  2000m_river zone  2000m_road struc  2000m_buildings
0         18.504713          0.320077         18.831700        62.182948
1         24.949599          0.057452         15.683638        59.148751
2         13.954671          0.503500         14.473403        70.907866
3         18.838494          0.392136         16.853148        63.755662
4         18.573028          0.384774         16.640350        64.241288

[5 rows x 24 columns]

In [24]:
final_station_df = final_station_df.drop(columns=[ 'item', 'mangName', 'year', 'addr'])

In [25]:
# dmX를 lat(위도)으로, dmY를 lon(경도)으로 이름 변경
final_station_df = final_station_df.rename(columns={
    'dmX': 'lat',
    'dmY': 'lon'
})

# 결과 확인
print(final_station_df[['station_id', 'lat', 'lon']].head())

   station_id        lat         lon
0           0  37.564639  126.975961
1           1  37.549389  126.971519
2           2  37.572025  127.005028
3           3  37.568650  126.998083
4           4  37.570633  126.996783

In [26]:
# 6. 최종 CSV 저장
final_station_df.to_csv('/Users/judetak/Desktop/산공카르텔경진대회/stations_with_landcover_buffers.csv', index=False, encoding='utf-8-sig')
print("작업 완료! 파일이 바탕화면에 저장되었습니다.")

작업 완료! 파일이 바탕화면에 저장되었습니다.

In [28]:
final_station_df.head()

,lat,stationName,lon,station_id,100m_greenspace,100m_river zone,100m_road struc,100m_buildings,500m_greenspace,500m_river zone,500m_road struc,500m_buildings,1000m_greenspace,1000m_river zone,1000m_road struc,1000m_buildings,2000m_greenspace,2000m_river zone,2000m_road struc,2000m_buildings
0,37.564639,중구,126.975961,0,39.091521,0.000000,28.052927,32.694990,14.518430,0.000000,25.608397,59.712613,9.314949,0.295662,29.108918,61.119910,18.504713,0.320077,18.831700,62.182948
1,37.549389,한강대로,126.971519,1,9.870937,0.000000,58.672330,31.296172,2.129878,0.000000,19.645211,78.064352,15.126995,0.000000,16.492650,68.219795,24.949599,0.057452,15.683638,59.148751
2,37.572025,종로구,127.005028,2,0.000000,0.000000,11.986298,87.853141,6.288148,0.976774,21.621246,70.953273,11.262965,0.632855,18.725218,69.218406,13.954671,0.503500,14.473403,70.907866
3,37.568650,청계천로,126.998083,3,0.000000,6.650604,34.888133,58.300702,7.652436,1.386342,23.188430,67.612231,9.121394,0.681107,22.726278,67.310660,18.838494,0.392136,16.853148,63.755662
4,37.570633,종로,126.996783,4,7.694860,0.000000,42.353424,49.791155,14.204926,1.292877,22.586301,61.755334,11.945378,0.693167,21.002850,66.198042,18.573028,0.384774,16.640350,64.241288